"""Ajout des colonnes start_time et end_time à VehicleLog

Revision ID: 5a86e8a3ef2a
Revises: b44cce88246a
Create Date: 2025-02-15 12:12:16.348419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a86e8a3ef2a'
down_revision = 'b44cce88246a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('released_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('released_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
