"""Ajout de end_time à VehicleLog

Revision ID: 9eec8f9b93c1
Revises: 5a86e8a3ef2a
Create Date: 2025-02-15 12:33:25.808350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eec8f9b93c1'
down_revision = '5a86e8a3ef2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_log', schema=None) as batch_op:
        batch_op.alter_column('mileage',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_log', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('mileage',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
